backend:
  name: git-gateway
  branch: main

locale: "ru"

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: simple

collections:

  - name: "pages"
    label: "Страницы сайта"
    files:

      - label: "Главная"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст", name: "body", widget: "markdown" }

      - label: "О фонде"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст", name: "body", widget: "markdown" }

      - label: "Помощь"
        name: "help"
        file: "content/help.md"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст", name: "body", widget: "markdown" }

      - label: "Реквизиты"
        name: "requisites"
        file: "content/requisites.md"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст", name: "body", widget: "markdown" }

      - label: "Контакты"
        name: "contacts"
        file: "content/contacts.md"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст", name: "body", widget: "markdown" }

      - label: "Пожертвования"
        name: "donate"
        file: "content/donate.md"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст", name: "body", widget: "markdown" }

  - name: "news"
    label: "Новости"
    label_singular: "Новость"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Фотография", name: "image", widget: "image", required: false }
      - { label: "Текст", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Проекты"
    label_singular: "Проект"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Фотография", name: "image", widget: "image", required: false }
      - { label: "Описание", name: "body", widget: "markdown" }

  - name: "documents"
    label: "Документы и отчёты"
    label_singular: "Документ"
    folder: "content/documents"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime", required: false }
      - { label: "Файл", name: "file", widget: "file" }
